//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Host.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://objecttransferservice.ru/", ConfigurationName="ServiceReference1.IObjectTransferService")]
    public interface IObjectTransferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/SayHello", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/SayHelloResponse")]
        string SayHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/SayHello", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/CreateList", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/CreateListResponse")]
        string CreateList(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/CreateList", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/CreateListResponse")]
        System.Threading.Tasks.Task<string> CreateListAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/CreateAccountingObject", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/CreateAccountingObjectResp" +
            "onse")]
        string CreateAccountingObject(string newAccountingObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/CreateAccountingObject", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/CreateAccountingObjectResp" +
            "onse")]
        System.Threading.Tasks.Task<string> CreateAccountingObjectAsync(string newAccountingObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/UpdateAccountingObject", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/UpdateAccountingObjectResp" +
            "onse")]
        string UpdateAccountingObject(string inventaryNumber, string accountingObjectData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/UpdateAccountingObject", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/UpdateAccountingObjectResp" +
            "onse")]
        System.Threading.Tasks.Task<string> UpdateAccountingObjectAsync(string inventaryNumber, string accountingObjectData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/DeleteAccountingObject", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/DeleteAccountingObjectResp" +
            "onse")]
        string DeleteAccountingObject(string inventaryNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://objecttransferservice.ru/IObjectTransferService/DeleteAccountingObject", ReplyAction="http://objecttransferservice.ru/IObjectTransferService/DeleteAccountingObjectResp" +
            "onse")]
        System.Threading.Tasks.Task<string> DeleteAccountingObjectAsync(string inventaryNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObjectTransferServiceChannel : Service.Host.ServiceReference1.IObjectTransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectTransferServiceClient : System.ServiceModel.ClientBase<Service.Host.ServiceReference1.IObjectTransferService>, Service.Host.ServiceReference1.IObjectTransferService {
        
        public ObjectTransferServiceClient() {
        }
        
        public ObjectTransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjectTransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectTransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string name) {
            return base.Channel.SayHello(name);
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync(string name) {
            return base.Channel.SayHelloAsync(name);
        }
        
        public string CreateList(string name) {
            return base.Channel.CreateList(name);
        }
        
        public System.Threading.Tasks.Task<string> CreateListAsync(string name) {
            return base.Channel.CreateListAsync(name);
        }
        
        public string CreateAccountingObject(string newAccountingObject) {
            return base.Channel.CreateAccountingObject(newAccountingObject);
        }
        
        public System.Threading.Tasks.Task<string> CreateAccountingObjectAsync(string newAccountingObject) {
            return base.Channel.CreateAccountingObjectAsync(newAccountingObject);
        }
        
        public string UpdateAccountingObject(string inventaryNumber, string accountingObjectData) {
            return base.Channel.UpdateAccountingObject(inventaryNumber, accountingObjectData);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAccountingObjectAsync(string inventaryNumber, string accountingObjectData) {
            return base.Channel.UpdateAccountingObjectAsync(inventaryNumber, accountingObjectData);
        }
        
        public string DeleteAccountingObject(string inventaryNumber) {
            return base.Channel.DeleteAccountingObject(inventaryNumber);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAccountingObjectAsync(string inventaryNumber) {
            return base.Channel.DeleteAccountingObjectAsync(inventaryNumber);
        }
    }
}
