//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectTransferWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public bool MessageType { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
    }
}
